sudo: required

services:
- docker

before_install:
- sudo apt-get update
- sudo apt-get install python-pip curl
- sudo pip install --upgrade pip
- sudo -H pip install --ignore-installed PyYAML
- sudo pip install yq
- KUBE_VERSION=$(curl -sl https://raw.githubusercontent.com/wise2c-dev/wise2c-config/master/config.yaml | yq -r '.branchs[] | select(.branch == "release-1.15")|.kube_version')

script:
- >
- docker build --build-arg KUBERNETES_VERSION=${KUBE_VERSION:1} -t wisecloud/kubeadm-version:${KUBE_VERSION} .
- docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
- docker push wisecloud/kubeadm-version:${KUBE_VERSION}
- docker run --rm --name=kubeadm-version wisecloud/kubeadm-version:${KUBE_VERSION} kubeadm config images list --kubernetes-version ${KUBE_VERSION:1}
- docker run --rm --name=kubeadm-version wisecloud/kubeadm-version:${KUBE_VERSION} kubeadm config images list --kubernetes-version ${KUBE_VERSION:1} --config=kube-dns.yaml