sudo: required

services:
- docker

before_install:
- sudo apt-get update
- sudo apt-get install python-pip curl
- sudo pip install -upgrade pip
- sudo pip install yq

script:
- >
- VERSION=$(curl -sl https://raw.githubusercontent.com/wise2c-dev/wise2c-config/master/config.yaml | yq -r '.branchs[] | select(.branch == "release-1.13")|.kube_version')
- docker build --build-arg KUBERNETES_VERSION=${VERSION:1} -t wisecloud/kubeadm-version:$VERSION .
- docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
- docker push wisecloud/kubeadm-version:$VERSION
- docker run --rm --name=kubeadm-version wisecloud/kubeadm-version:$VERSION kubeadm config images list --kubernetes-version ${VERSION:1}
